### ISSUE TITLE
[BUG] If variable exists but is empty, set:env creates a new variable instead of updating existing variable

### ISSUE THREAD

**Issue by ddavaham** [imliam/laravel-env-set-command#3]
My current .env file contains variables that need to be filled in by the user when setting up the application. These variable are just set to empty strings. 
```
MAILHEADER_PAGES=
```
Using your library, if I attempt to fill this variable
```
php artisan env:set mailheader_pages 7
A new environment variable with key 'MAILHEADER_PAGES' has been set to '7'
```
resulting in 

```

MAILHEADER_PAGES=

MAILHEADER_PAGES=7
```

I narrowed down the bug to [line 50 of EnvironmentSetCommand.php](https://github.com/ImLiam/laravel-env-set-command/blob/master/src/EnvironmentSetCommand.php#L50).

```
if ($oldValue = $this->getOldValue($contents, $key)) {
    $contents = str_replace("{$key}={$oldValue}", "{$key}={$value}", $contents);
    $this->writeFile($envFilePath, $contents);
    return $this->info("Environment variable with key '{$key}' has been changed from '{$oldValue}' to '{$value}'");
}
```

This line calls getOldValue which returns the position in the string at which the old value starts. In my case, if the oldValue is an empty string, then this evaluates to false, which in turn skips over this if block and creates a new value.

**Comment by imliam** [comment]
This has been fixed with version v1.1 and it now consistently sets the existing key instead of adding a new one.
