### ISSUE TITLE
In which case it actually works?

### ISSUE THREAD

**Issue by worldofswift** [imliam/laravel-env-set-command#6]
One part of this issue related to sibling issue:
1. The empty variable doesn't become settable but a new one created instead.

2. Actually I try to reset it `APP_URL=NOT_SET_YET` to new value for example using 
`docker exec -i $container_name php artisan env:set APP_URL $(aws ssm get-parameter --name APP_URL --with-decryption --region ${region} --query "Parameter.[Value]" --output text)`
which actually calls to `php artisan env:set APP_URL 'some url'`. But it doesn't change value at all to provided one.

**Comment by imliam** [comment]
Sorry for the late response to this issue. If this is still a problem in the latest version please raise a new ticket, however I have just manually tested this case on v1.1 and it works as intended.
