### ISSUE TITLE
Broken on Laravel 6.x

### ISSUE THREAD

**Issue by Smankusors** [imliam/laravel-env-set-command#9]
When I want to set the env, there's an error : `Call to undefined function ImLiam\EnvironmentSetCommand\str_contains()`

On the Laravel 6.x, this helper function has been renamed to [`Str::contains`](https://laravel.com/docs/master/helpers#method-str-contains)

And.... I don't think this repo will have another commit other than initial commit?

Thanks,

**Comment by Syourt** [comment]
@Smankusors I have created a pull request to solve this issue. Hopefully it'll be merged soon.

https://github.com/imliam/laravel-env-set-command/pull/10

**Comment by Smankusors** [comment]
@imliam is this project still ongoing?

**Comment by Smankusors** [comment]
it's been nearly 1 month, I abandoned this command. My project env will be handled by another program outside Laravel.

**Comment by imliam** [comment]
Sorry about the delay. Thanks to #13 the package now runs on newer versions of Laravel.
